### ISSUE TITLE
Cannot find std headers when using libclang

### ISSUE THREAD

**Issue by jdumas** [niosus/EasyClangComplete#181]
On my computer (up to date Archlinux), the following MWE doesn't agree with EasyClangComplete if I set `"libclang": true`:

```cpp
#include <vector>

int main(void) {
	std::vector<int> foo;
	foo.emplace_back(2);
	return 0;
}
```

With a simple CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)
add_executable(${PROJECT_NAME} main.cpp)
```

And my settings for EasyClangComplete:

```json
{
	"common_flags" : [],
	"c_flags" : [],
	"cpp_flags" : [],
	"use_libclang" : true,
	"verbose" : true,
}
```

And here is a screenshot of the observed behavior on my system:
![2016-12-16-150010_3120x1920_scrot](https://cloud.githubusercontent.com/assets/578702/21265377/6b7b176e-c3a1-11e6-92b5-c6667be96f75.png)

If I switch to `"use_libclang" : false`, then it works somehow...

**Comment by simia** [comment]
Have you tried adding flag --std=c++11?

**Comment by niosus** [comment]
Also, it is probably related to #88 
you should manually point the plugin to standard headers.

**Comment by niosus** [comment]
> If I switch to "use_libclang" : true, then it works somehow...

You meant to `false`?

**Comment by jdumas** [comment]
> You meant to false?

Yes sorry, I edited my message.

I shouldn't have to point the plugin to the standard header or to set `-std=c++11`. What is the point of having a `CMakeLists.txt` if I need to specify additional headers to the plugin? Moreover, it /does/ work with `"libclang": false`, so there must be another something else.

The same issues appears with other libs even if they are specified in my `CMakeLists.txt` (e.g. `#include <Eigen/Dense>`).

**Comment by niosus** [comment]
Yes, you are right. You should not specify anything. However, because of the bug in clang referenced in #88 you need to specify this location for `libclang` for now. This bug is fixed for clang 4.0 and will go away as soon as they release a new version.

**Comment by niosus** [comment]
Can you also show your `CMakeLists.txt`? It is strange as it seems clang is able to find vector, but not the emplace. So it seems it really doesn't understand this is c++11 code. And also, as usual, the log in sublime text console since a cold start to the point when it shows error. Thanks!

**Comment by jdumas** [comment]
Hi, you are right that there was a problem with `C++11`, but I don't understand why this would have been working via the command line (without libclang). Maybe my system `clang` is compiling in C++11 by default but I don't remember doing any particular setting in that regard.

Ok, so if I add C++11 to the `CMakeLists.txt`, it works for `emplace_back()`:

```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)
add_executable(${PROJECT_NAME} main.cpp)
target_include_directories(${PROJECT_NAME} PUBLIC /usr/include/eigen3)
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD 11)
set_target_properties(${PROJECT_NAME} PROPERTIES CXX_STANDARD_REQUIRED ON)
```

But now, I still get an error with types from Eigen, as shown here (starting from a cold start):
![2016-12-16-170502_3120x1920_scrot](https://cloud.githubusercontent.com/assets/578702/21269325/9de74392-c3b2-11e6-8b37-5e7cd6868f84.png)


The log in the console in very long and doesn't fit in a screenshot, so let me know how I can copy it if you need the full log.

**Comment by niosus** [comment]
Just select it, copy and paste here as code:
```
<log>
```

**Comment by niosus** [comment]
as a side note. Any reason why you are not using `find_package(Eigen3)`? I use this in my code and it works fine.

**Comment by jdumas** [comment]
I just didn't want to bother including the FindEigen3.cmake in my test project, but usually that is what I do yes (I reckon Eigen ships with a CMake config only since version 3.3).

**Comment by niosus** [comment]
Ok, got that. Find Eigen works well with Eigen 3.2 too.

Anyway, please publish the log. Don't worry if it is long. I will cut unneeded parts.

**Comment by jdumas** [comment]
```
DPI scale: 0.906
startup, version: 3126 linux x64 channel: stable
executable: /opt/sublime_text_3/sublime_text
working dir: /home/jdumas
packages path: /home/jdumas/.config/sublime-text-3/Packages
state path: /home/jdumas/.config/sublime-text-3/Local
zip path: /opt/sublime_text_3/Packages
zip path: /home/jdumas/.config/sublime-text-3/Installed Packages
ignored_packages: ["LaTeXTools", "Pylinter", "Python", "SublimeLinter", "SublimeLinter-contrib-clang", "SublimeLinter-contrib-cmakelint", "SublimeLinter-lua", "Vintage", "YcmdCompletion"]
pre session restore time: 0.120051
loading dictionary Packages/Language - English/en_US.dic
startup time: 0.275149
first paint time: 0.287869
first paint time: 0.296771
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin ANSIescape.ansi
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.changes
reloading plugin ApplySyntax.support
reloading plugin AutoDocstring.auto_docstring
reloading plugin AutoDocstring.docstring_styles
reloading plugin AutoDocstring.dparse
reloading plugin BeautifyLatex.beautify_latex
reloading plugin CMakeEditor.CMakeEditor
reloading plugin Clang Format.clang_format
reloading plugin Dictionaries.Dictionaries
reloading plugin DoxyDoxygen.Doxy
------==== DoxyDoxygen plugins loaded ====------
0 sub-modules to reload
reloading plugin LanguageTool.LTServer
reloading plugin LanguageTool.LanguageList
reloading plugin LanguageTool.LanguageTool
reloading plugin MagicPython.sublime
reloading plugin Markdown Preview.MarkdownPreview
reloading plugin Markdown Preview.helper
reloading plugin Markdown Preview.markdown_settings
reloading plugin Markdown Preview.markdown_wrapper
reloading plugin MarkdownEditing.bootstrap
reloading plugin MarkdownEditing.custom_find_under_expand
reloading plugin MarkdownEditing.decide_title
reloading plugin MarkdownEditing.distraction_free_mode
reloading plugin MarkdownEditing.footnotes
reloading plugin MarkdownEditing.indent_list_item
reloading plugin MarkdownEditing.indent_list_multiitem
reloading plugin MarkdownEditing.lint
reloading plugin MarkdownEditing.mdeutils
reloading plugin MarkdownEditing.numbered_list
reloading plugin MarkdownEditing.quote_indenting
reloading plugin MarkdownEditing.references
reloading plugin MarkdownEditing.switch_list_bullet_type
reloading plugin MarkdownEditing.underlined_headers
reloading plugin Non Text Files.NonTextFiles
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Preset Command.Preset Command
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin EasyClangComplete.EasyClangComplete
reloading plugin IntelliDocs.intellidocs
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin Terminal.Terminal
plugins loaded
updating ANSI build settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  autocomplete_all           <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  c_flags                    <-- '[]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  clang_binary               <-- 'clang++'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  common_flags               <-- '[]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  cpp_flags                  <-- '[]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  errors_on_save             <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  flags_sources              <-- '[{'file': 'CMakeLists.txt'}, {'file': 'compile_commands.json'}, {'file': '.clang_complete'}]'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  hide_default_completions   <-- 'False'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_folder        <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  include_file_parent_folder <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  max_cache_age              <-- '00:30:00'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  triggers                   <-- '['.', '->', '::']'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  use_libclang               <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage:  verbose                    <-- 'True'
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.EasyClangComplete: on_activated_async view id 28
DEBUG:EasyClangComplete.plugin.settings.settings_manager: no settings for view 28. Reinitializing.
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Overriding settings by project ones if needed:
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Valid prefixes: ['ecc_', 'easy_clang_complete_']
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Reading settings...
DEBUG:EasyClangComplete.plugin.settings.settings_storage: Settings sucessfully read...
INFO:EasyClangComplete.plugin.tools: Getting version from command: `clang++ -v`
INFO:EasyClangComplete.plugin.tools: Found clang version: 3.9.0
DEBUG:EasyClangComplete.plugin.settings.settings_storage: populating common_flags with current variables.
DEBUG:EasyClangComplete.plugin.settings.settings_manager: settings initialized for view: 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.view_config: generate new config for path: 28
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
INFO:EasyClangComplete.plugin.view_config: init completer based on libclang
DEBUG:EasyClangComplete.plugin.completion.lib_complete: using bundled cindex: EasyClangComplete.clang.cindex39
DEBUG:EasyClangComplete.clang.utils: platform: ('64bit', '')
DEBUG:EasyClangComplete.clang.utils: python version: 3.3.6
INFO:EasyClangComplete.clang.utils: we are on 'Linux'
INFO:EasyClangComplete.clang.utils: searching for: 'libclang.so'
INFO:EasyClangComplete.clang.utils: libclang search output = '/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib64/libclang.so'
DEBUG:EasyClangComplete.clang.utils: real output: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib64/libclang.so
INFO:EasyClangComplete.clang.utils: found libclang dir: '/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/6.2.1/../../../../lib64'
INFO:EasyClangComplete.clang.utils: found library file: 'libclang.so'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[get]: for file /home/jdumas/downloads/test_cpp/main.cpp
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[cached]: 'None'
DEBUG:EasyClangComplete.plugin.tools: searching 'CMakeLists.txt' from '/home/jdumas/downloads/test_cpp' to '/home/jdumas/downloads/test_cpp'
DEBUG:EasyClangComplete.plugin.tools: found 'CMakeLists.txt' file: /home/jdumas/downloads/test_cpp/CMakeLists.txt
DEBUG:EasyClangComplete.plugin.tools: found needed line: 'project(foo)
'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[current]: '/home/jdumas/downloads/test_cpp/CMakeLists.txt'
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: [cmake]:[generate new db]
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: Folder /tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038 exists.
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: prefix paths: []
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: merged paths: 
DEBUG:EasyClangComplete.plugin.flags_sources.cmake_file: CMAKE_PREFIX_PATH: 
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: running command: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  "/home/jdumas/downloads/test_cpp"
INFO:EasyClangComplete.plugin.flags_sources.cmake_file: cmake produced output: 
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038

DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeCache.txt'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/home/jdumas/downloads/test_cpp/CMakeLists.txt'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/3.6.3/CMakeCCompiler.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/3.6.3/CMakeCXXCompiler.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/3.6.3/CMakeSystem.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeCInformation.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeCXXInformation.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeCommonLanguageInclude.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeGenericSystem.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeLanguageInformation.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeSystemSpecificInformation.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/CMakeSystemSpecificInitialize.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Compiler/GNU-C.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Compiler/GNU-CXX.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Compiler/GNU.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Platform/Linux-GNU-C.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Platform/Linux-GNU-CXX.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Platform/Linux-GNU.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Platform/Linux.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/usr/share/cmake-3.6/Modules/Platform/UnixPaths.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/cmake.check_cache'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/CMakeDirectoryInformation.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/CMakeFiles/foo.dir/DependInfo.cmake'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/home/jdumas/downloads/test_cpp/CMakeLists.txt'
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[get]: for file /home/jdumas/downloads/test_cpp/main
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[cached]: 'None'
DEBUG:EasyClangComplete.plugin.tools: searching 'compile_commands.json' from '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038' to '/'
DEBUG:EasyClangComplete.plugin.tools: found 'compile_commands.json' file: /tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/compile_commands.json
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[current]: '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/compile_commands.json'
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]:[load new]
DEBUG:EasyClangComplete.plugin.flags_sources.compilation_db: [db]: put into cache: '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/compile_commands.json'
DEBUG:EasyClangComplete.plugin.tools: updating modification time for file '/tmp/EasyClangComplete/cmake_builds/bf83f1fe76109dc1ca2fa4b7b99db038/compile_commands.json'
DEBUG:EasyClangComplete.plugin.view_config: flags generated from 'CMakeLists.txt'.
DEBUG:EasyClangComplete.plugin.completion.lib_complete: view is 28
DEBUG:EasyClangComplete.plugin.completion.lib_complete: translation unit does not exist. Creating.
DEBUG:EasyClangComplete.plugin.tools: file has valid syntax: `C++`
DEBUG:EasyClangComplete.plugin.completion.lib_complete: clang flags are: ['-c', '-fsyntax-only', '-x', 'c++', '-I/home/jdumas/downloads/test_cpp', '-I/home/jdumas/downloads', '-I/usr/include/eigen3', '-std=gnu++11']
DEBUG:EasyClangComplete.plugin.completion.lib_complete: compilation started for view id: 28
DEBUG:EasyClangComplete.plugin.completion.lib_complete: compilation done in 0.42156004905700684 seconds
DEBUG:EasyClangComplete.plugin.completion.lib_complete: reparsing translation_unit for view 28
DEBUG:EasyClangComplete.plugin.completion.lib_complete: reparsed in 0.5897023677825928 seconds
DEBUG:EasyClangComplete.plugin.error_vis: generating error regions for view 28
DEBUG:root: adding error {'error': "'stdarg.h' file not found", 'row': '39', 'file': '/usr/include/wchar.h', 'col': '11'}
DEBUG:root: adding error {'error': "member reference base type 'Eigen::Vector3d' (aka 'int') is not a structure or union", 'row': '6', 'file': '/home/jdumas/downloads/test_cpp/main.cpp', 'col': '3'}
DEBUG:EasyClangComplete.plugin.error_vis: 1 error regions ready
DEBUG:EasyClangComplete.plugin.error_vis: showing error regions: [(80, 81)]
DEBUG:EasyClangComplete.plugin.view_config: starting timer to remove old configs.
DEBUG:EasyClangComplete.plugin.view_config: [timer]: start for view: 28
DEBUG:EasyClangComplete.plugin.view_config: [timer]: active for views: dict_keys([28])
```

**Comment by niosus** [comment]
Hmm, so `'-I/usr/include/eigen3'` flag is there. So the plugin does what it must. This means the issue is somewhere in clang. This looks suspicious:

```
DEBUG:root: adding error {'error': "'stdarg.h' file not found", 'row': '39', 'file': '/usr/include/wchar.h', 'col': '11'}
```

Can you try to add this to your common flags?
```
"-I/usr/lib/clang/$clang_version/include"
```

**Comment by jdumas** [comment]
Interesting, it appears to be working with `"-I/usr/lib/clang/$clang_version/include"`.

**Comment by niosus** [comment]
As far as I understand this should be fixed with #88. I will close this issue for now.
