### ISSUE TITLE
Compilation fails when file name is not the last in the command entry of the compilation database

### ISSUE THREAD

**Issue by matreshkin** [niosus/EasyClangComplete#665]
# System info: #
- Sublime Text version: 3210
- Which system are you on: Ubuntu 18
- Clang version: 7.0.0

# What happens:  #
Cannot detect a reason of the error while compileing with libclang and custom combdb target.
Project settings:
```

  "settings":
  {
    "ecc_flags_sources": [
        {
          "file": "compile_commands.json",
          "search_in": "${project_path}/../",
        },
      ],
  },
```
Meanwhile:
- using clang binary works (```"ecc_use_libclang" : false,  "ecc_show_type_info": false,```)

I cannot show the compiler flags since NDA reasons, but debugging it by my own is also impossible.
If you have an idea how to look inside the compilation process to reveal the issue, please help.
At last chance I will try to fork and debug this plugin in case of having free time.

<details>
<summary>Log that illustrates the issue: </summary>
  
```
[ECC:DEBUG]:[view_config.py]:[__generate_essentials]:[Thread-18]: Appending and filtering flags with ignore patterns: ['some_flag_pattern*', '-W_other_pattern_$project_path*']
[ECC:DEBUG]:[view_config.py]:[needs_update]:[Thread-18]: different completer class. Need to update.
[ECC:DEBUG]:[view_config.py]:[update_if_needed]:[Thread-18]: config needs new completer.
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-18]: view is 116
[ECC:DEBUG]:[lib_complete.py]:[update]:[Thread-18]: translation unit does not exist. Creating.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-18]: clang flags are: [ MANY MANY flags that I cannot expose ]
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-18]: compilation started for view id: 116
[ECC:ERROR]:[lib_complete.py]:[parse_tu]:[Thread-18]: error while compiling: Error parsing translation unit.
[ECC:DEBUG]:[lib_complete.py]:[parse_tu]:[Thread-18]: compilation done in 0.002574443817138672 seconds
[ECC:CRITICAL]:[lib_complete.py]:[update]:[Thread-18]:  cannot create translation unit. Abort.
[ECC:DEBUG]:[file.py]:[update_mod_time]:[Thread-18]: updating modification time for file '.../File.cc'
[ECC:DEBUG]:[EasyClangComplete.py]:[config_updated]:[Thread-18]: updated config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x7fca4f0ca5d0>
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-9]: config exists for view: 116
[ECC:DEBUG]:[view_config_manager.py]:[get_from_cache]:[Dummy-9]: config: <EasyClangComplete.plugin.view_config.view_config.ViewConfig object at 0x7fca4f0ca5d0>
[ECC:DEBUG]:[subl_bridge.py]:[get_view_lang]:[Dummy-9]: ECC does nothing for language syntax: 'JSON (Sublime)'
```

</details>

**Comment by niosus** [comment]
Usually this means that some of the flags are malformed. Are you using any common flags? Are you sure all -I flags actually have the -I prefix before them? 

Debugging this kind of issues is hard. What I usually do is:
- As the first step, call "show all errors" command and see the first one. It might give some hints on what is happening. Usually, this type of errors comes from some gcc/clang/<your_compiler/ incompatibility.
- As a second step, I usually take all the flags, dump them into file, then use them with a clang binary to verify that it builds. If that does not build, as least I now have a reproducible case.
- Otherwise, try to bisect your flags and find the offending ones. :man_shrugging:

**Comment by matreshkin** [comment]
Thanks for the reply,
I managed to compile the file with libclang after I moved out the source file path itself from compiler flags.
i.e. was : 
```
    {
        "command": "clang++ --target=x86_64-linux-gnu --sysroot=... -B... -c -o /home/po.cc.o /home/po.cc -I... ... ",
        "directory": "/home/po",
        "file": "/home/po/File.cc"
    },
```
and became
```
    {
        "command": "clang++ --target=x86_64-linux-gnu --sysroot=... -B... -c -o /home/po.cc.o -I... ... ",
        "directory": "/home/po",
        "file": "/home/po/File.cc"
    },
```
Now the parsing error is gone and libclang can continue parsing. 
Is it as intended or there may be another bug somewhere?

I got a lot of 'not found' errors after having compilation work, so the source path in flags might not be the root problem/

**Comment by matreshkin** [comment]
> I got a lot of 'not found' errors after having compilation work, so the source path in flags might not be the root problem.
That problem was caused by use_default_includes=false. All requiered pathes are in the flags (and they are properly used by `clang_binary`), thus I can create another bug if it sounds sensible.

**Comment by niosus** [comment]
Ah, so if I understand correctly, the issue was that the `*.cc` file was not the last one in the command?

**Comment by matreshkin** [comment]
The issue was that .cc file WAS in the command. Just removing file fixed compilation.
I'll check whether moving it after all flags helps.

**Comment by niosus** [comment]
Well, the cc file should always be in the command as otherwise it is malformed. I might need to implement a more robust way of detecting the compiled file, e.g. it doesn't have any prefix in front if it, but this might take some time to implement.

**Comment by niosus** [comment]
Also, an important question @matreshkin: does the file in the `command` line have exactly the same path as the one in `file` entry? I am thinking of an easier way to filter that one out.

**Comment by niosus** [comment]
Also, would you mind testing if PR #673 does the trick for you?

**Comment by niosus** [comment]
Should be fixed in the above-mentioned PR. Please reopen if there is still problem with it.

**Comment by matreshkin** [comment]
Sorry for not responding - I've been extremely busy recently.
Now the compilation is done (there are still many "Not found" problems though that I'll investigate later).

Thanks a lot again, answers and fixes are just invaluable for all us

**Comment by niosus** [comment]
No worries. Feel free to reopen if you still see the issues.

**Comment by matreshkin** [comment]
Eventually, the problem is still in `use_default_includes=false`. With 'use_default_includes=true', libclang variant gives the same result as clang_binary does (and which is the expected behavior).
And I am not sure whether it is a bug or not.

I looked at the description of 'use_default_includes' but I haven't got the idea and why it it can be needed. I suspect, some pre-work is done for libclang input when `use_default_includes=true`, and this work is required.

However, if libclang must work with `use_default_includes=false` as well as clang binary, I'll try to find a simple reproduction and fill a new bug.

**Comment by niosus** [comment]
So do I understand correctly, that now it works for you? 

I am a bit confused about your message, as the `"use_default_includes"` is by default `true` :thinking: 

The flag is basically only there to allow people who know exactly which set of flags they want to achieve to actually get that set of flags with no default flags added to the command line. It should generally remain untouched.

**Comment by matreshkin** [comment]
Everything is allright then)
I turned it off while was fightening the original problem.
If "use_default_includes" must be True and shouldn't be nomally touched, then there is no  issue at all and libclang variant works as expected.
Thanks:)

**Comment by niosus** [comment]
Happy to hear that!
